//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4984
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=2.0.50727.42。
// 
namespace UpdateAssistant {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UpdatePackageConfig {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedTerminateProcessNames", Order=0)]
        public string[] NeedTerminateProcessNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedTerminateJavaProcessNames", Order=1)]
        public string[] NeedTerminateJavaProcessNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedBackupDirNames", Order=2)]
        public string[] NeedBackupDirNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedIgnoreBackupFileNames", Order=3)]
        public string[] NeedIgnoreBackupFileNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedCleanInstallPathDirNames", Order=4)]
        public string[] NeedCleanInstallPathDirNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public UpdatePackageConfigUpdatePackageContaint UpdatePackageContaint;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UpdateDBScriptFiles", Order=6)]
        public string[] UpdateDBScriptFiles;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedStartProgressNames", Order=7)]
        public string[] NeedStartProgressNames;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedStartWindowsServices", Order=8)]
        public string[] NeedStartWindowsServices;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedCleanTempDirs", Order=9)]
        public string[] NeedCleanTempDirs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NeedCleanTempFiles", Order=10)]
        public string[] NeedCleanTempFiles;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class UpdatePackageConfigUpdatePackageContaint {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dirs", Order=0)]
        public string[] Dirs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Files", Order=1)]
        public string[] Files;
    }
}
